* 7. Вход и изход

  Съществуват няколко начина да се представи изхода на една програма:
  данните могат да бъдат изведени в подходяща за четене от човек
  форма, или да бъдат записани във файл за бъдеща употреба.  Тази
  глава ще обсъди някои от възможностите.

** 7.1. По-гиздаво форматиране на изхода

   Дотук срещнахме два начина за извеждане на стойности: /изразите/ и
   конструкцията `print'.  (Трети начин е да се използването на метода
   `write()' на файловите обекти — към файла на стандартния изход
   можете да се обръщате чрез `sys.stdout'.  Вижте Library Reference
   за повече информация по този въпрос.)

   Често бихте желали повече контрол върху форматирането на вашия
   изход, вместо простото извеждане на стойности, разделени с
   интервал.  Съществуват два начина да форматирате изхода.  Първият е
   да изпълните сами цялото управление на символните низове – чрез
   изрязване и съединяване на символни низове можете да създадете
   всеки изглед, който пожелаете.  Стандартният модул `string' съдържа
   няколко полезни операции за допълване на символни низове до даден
   размер на колона.  Това ще бъде обсъдено след малко.  Вторият начин
   е да използвате 

   
   е да използвате оператора % със символен низ като ляв аргумент.
   Операторът % интерпретира левия аргумент като форматиращ символен
   низ много подобен на sprintf() в C, който да бъде приложен към
   десния аргумент, и връща символния низ, получен от тази форматираща
   операция.

